<%@ Page Title="Home Page" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Default.aspx.cs" Inherits="CulinaryDelight._Default" %>


<asp:Content runat="server" ID="FeaturedContent" ContentPlaceHolderID="FeaturedContent">
    <section class="featured" style="background-color: #FFFFFF">

    </section>
</asp:Content>

<asp:Content runat="server" ID="BodyContent" ContentPlaceHolderID="MainContent">
    <div role="banner" style="text-align: center; border: medium double #808080; padding: 2px; margin: 2px; display: block; float: left; cursor: crosshair">

           <asp:UpdatePanel ID="UpdatePanel1" runat="server">
               <ContentTemplate>
                    <asp:Timer ID="Timer1" runat="server" Interval="3000" OnTick="Timer1_Tick"></asp:Timer>
            <asp:Image ID="Image1" Height="200px" Width="200px" runat="server" ImageAlign="Middle" />
               </ContentTemplate>
           </asp:UpdatePanel>
       
    </div>
      <div style="font-family: Pristina; font-size: large; font-style: italic;"><br /> <h3>We have the collection of the best tastes in town that will tickle your taste buds. 
            Allow us to serve you once and you'll be convinced! 
            Our recipes are authentic, time-tested and prepared by Chefs of the same community. 
            Birthdays or Brit / Baby-naming celebrations / Bar and Bat Mitzvah Stag and Bachelorette Parties or Team-building parties or 
            New job celebrations … in fact any reason in the world for a party! </h3>

        </div>   
    <br /><br /><br /><br /> 
    <hr />    
    <div id="SriLankan">
        <table>
            <td>
        <img id="sl" src="Images/4.jpg" /></td><td><span style="font-family: Kalinga">Sri Lankan cuisine is one of the most complex cuisines of South Asia. 
            Due to its proximity to South India, the cuisine of Sri Lanka shows some influence, yet is in many ways quite distinct. 
            As a major trade hub, it draws influence from colonial powers that were involved in Sri Lanka and by foreign traders. 
            Rice, which is consumed daily, can be found at any occasion, while spicy curries are favorite dishes for lunch and dinner.
            Some of the Sri Lankan dishes have striking resemblance to Kerala cuisine, 
            which could be due to the similar geographic and agricultural features with Kerala.</span></td></table>
    </div>
    <div id="gujarati">
        <table>
            <td>
       <img id="gj" src="Images/8.jpg" /></td><td> <span style="font-family: Kalinga">Despite having an extensive coastline for seafood, it is primarily a vegetarian cuisine due to the influence of Jain vegetarianism and traditional Hinduism.
            The typical Gujarati Thali consists of Rotli, Dal or Kadhi, Rice, and Shaak/Sabzi (a dish made up of different combinations of vegetables and spices, which may be spicy or sweet). 
            Gujarati cuisine varies widely in flavour and heat, depending on a given family's tastes as well as the region of Gujarat they are from. 
            North Gujarat, Kathiawad, Kachchh, and Surti Gujarat are the four major regions of Gujarat that all bring their own style to Gujarati food. 
            Many Gujarati dishes are distinctively sweet, salty, and spicy at the same time.</span></td></table>
    </div>
    <div id="tandoori">
        <table>
            <td>
      <img id="td" src="Images/13.jpg" /></td><td style="font-family: kalinga"> <span>The tandoor is used for cooking in Southern, Central and Western Asia. 
            The heat for a tandoor was traditionally generated by a charcoal or wood fire, burning within the tandoor itself, thus exposing the food to live-fire, radiant heat cooking, and hot-air, convection cooking, and smoking by the fat and food juices that drip on to the charcoal.
            Temperatures in a tandoor can approach 480 °C (900 °F), and it is common for tandoor ovens to remain lit for long periods to maintain the high cooking temperature. 
            The tandoor design is something of a transitional form between a makeshift earth oven and the horizontal-plan masonry oven.</span>
            </td></table>
             </div>
     
    </asp:Content>
<asp:Content ID="Content1" runat="server" contentplaceholderid="HeadContent">
    <style type="text/css">
        #td {
            width: 200px;
            height: 182px;
        }
        #sl {
            height: 182px;
            width: 200px;
        }
        #gj {
            width: 199px;
        }
    </style>
</asp:Content>
